## Rule-based cleaning

In [1]:
import pandas as pd

# df = pd.read_csv('your_data.csv')  # гээд датагаа уншуулсан гэж үзье

In [ ]:
# df маань Address гэсэн баганатай гэж үзье
# Address баганы утганд үндэслэн дүүрэгт хуваацгаая

df.loc[df['Address'].str.contains('ЧД|ЧИН|CHIN|ДЭНЖИЙН 1000|ДЭНЖИЙН МЯНГ|Д-1000|ХАЙЛААСТ|БАЯНБҮРД|БАЯНБVРД|УЛСЫН ИХ ДЭЛГ|УИД|ТЭНГИС КИНО Т', case=False), 'Section'] = 'Чингэлтэй' 
df.loc[df['Address'].str.contains('СБД|СҮХБАА|SBD|SUKHBAA|SUHBAA|SVKHBAA|SVHBAA|4-Р ДЭЛГVV|4-Р ДЭЛГҮҮ|100 АЙЛ|ЗУУН АЙЛ|ХАНГАЙ ХОТ|ДӨЛГӨӨН НУУР|ХҮҮХДИЙН 100', case=False), 'Section'] = 'Сүхбаатар' 
df.loc[df['Address'].str.contains('БЗД|БАЯНЗҮ|BZD|BAYNZU|BAYNZV|BAYANZU|BAYANZV|САНСАР|16-Р ХОРООЛ|ОЮУТНЫ ХОТХОН|ЦАЙЗ|ШАР ХАД|ХУЖИРБУЛАН|13-Р ХОРООЛ|15-Р ХОРООЛ|БОТАНИК|ГАЧУУРТ|ЗҮҮН 4|ЗVVН 4|ЖУКОВ|ОФИЦЕР|МАРШАЛ ТАУН|БАЯНМОНГОЛ ХОРООЛ', case=False), 'Section'] = 'Баянзүрх' 
df.loc[df['Address'].str.contains('СХД|СОНГИНО|SHD|SONGINO|БАЯН ХОШУУ|БАЯНХОШУУ|1-Р ХОРООЛ|ОРБИТ|САППОРО|22-Н ТОВЧОО|5 ШАР|5-Н ШАР|БАРУУН САЛАА|ДРАГОН|22 ТОВЧОО', case=False), 'Section'] = 'Сонгинохайрхан' 
df.loc[df['Address'].str.contains('БГД|БАЯНГО|BGD|BAYNGO|БАРС ЗАХ|ТӨМӨР ЗАМ|3-Р ХОРООЛ|3, 4-Р ХОРООЛ|4-Р ХОРООЛ|ГЭМТЭЛ|ГЭМТЛИЙН|10-Р ХОРООЛ|10 ХОРООЛ|БАРС 2|БАРС-2|АЛТАЙ ХОТХОН|БИЧИЛ|ГАНДАН|ТБД АНД|МОДНЫ 2', case=False), 'Section'] = 'Баянгол' 
df.loc[df['Address'].str.contains('ХУД|ХАН-|ХАНУУ|ХАН УУ|HUD|HAN-|HANUU|Яармаг|YAARMA|YARMAG|120 МЯНГАТ|120-Н МЯНГАТ|ӨЛЗИЙТ ХОРОО|19-Р ХОРООЛ|ЗАЙСАН|RIVER GARDEN|НИСЭХ', case=False), 'Section'] = 'Хан-Уул' 
df.loc[df['Address'].str.contains('НАЛАЙХ|NALAI', case=False), 'Section'] = 'Налайх' 
df.loc[df['Address'].str.contains('БАГАНУУР|BAGANUUR', case=False), 'Section'] = 'Багануур' 
df.loc[df['Address'].str.contains('ТӨВ АЙМ|ТӨВ-АЙМ', case=False), 'Section'] = 'Төв'

### Дээрх кодны тайлбар

pandas.Series.str accessor нь текст боловсруулахад ашиглагддаг.
Нэмэлт мэдээлэл, зааврыг [Python | Pandas Working With Text Data](https://www.geeksforgeeks.org/pandas/python-pandas-working-with-text-data/)

In [ ]:
df['addr_lower'] = df['Address'].str.lower()  # Address баганы бүх үсгийг жижиг үсэг болгож addr_lower баганад хадгална
df['addr_upper'] = df['Address'].str.upper()  # Address баганы бүх үсгийг том үсэг болгож addr_upper баганад хадгална

df['Address'] = df['Address'].str.upper()     # Address баганы бүх үсгийг том үсэг болгож өөрт нь хадгална

df['Address'] = df['Address'].str.strip()     # Address баганы утгын эхэнд болон төгсгөлд байгаа хоосон зайг арилгана. Жишээлбэл '  123 -р байр ' => '123 -р байр'

df['Address'] = df['Address'].str.replace('-', ' ')   # Address баганы утганд байгаа бүх '-' тэмдэгтийг хоосон зайгаар солих. Жишээлбэл '123-р байр' => '123 р байр'

df['Address'].str.contains('САНСАР|ЖУКОВ')    # Address баганы утганд 'САНСАР' эсвэл 'ЖУКОВ' гэсэн үг агуулагдаж байгаа эсэхийг шалгана. Үр дүн нь True буюу False байна
                                              # Хэрвээ энэ нөхцөл үнэн бол тухайн мөрийн утгаас 'Section' багананд 'Баянзүрх' гэсэн утга оруулах жишээний кодыг дээр харуулсан
                                              # case=False гэж бичвэл том жижиг үсэг ялгахгүй шалгана


df['Address'].str.startswith('БЗД')           # Address баганы утга 'БЗД' гэсэн үгээр эхэлж байгаа эсэхийг шалгана. Үр дүн нь True буюу False байна
df['Address'].str.endswith('ХОРООЛ')          # Address баганы утга 'ХОРООЛ' гэсэн үгээр төгсөж байгаа эсэхийг шалгана. Үр дүн нь True буюу False байна

# --------------------------------------------------
# "|" (pipe) тэмдэг гэж юу вэ?
# --------------------------------------------------
# Regex дээр "|" нь OR гэсэн утгатай
#
# "ЧД|ЧИН|CHIN" гэвэл:
#   - ЧД
#   - ЧИН
#   - CHIN
# эдгээрийн аль нэг нь байвал таарна гэсэн үг
#--------------------------------------------------
# Харин "&" (ampersand) тэмдэг нь AND гэсэн утгатай
# "ЧД&1000" гэвэл:
#   - ЧД ба 1000 гэсэн үг хоёр нь байвал таарна
# --------------------------------------------------

### Өгөгдөл цэвэрлэх процесс

Хаяг цэвэрлэх хэрэгтэй гэж бодъё. Тэгвэл бид хамгийн түрүүнд өөрсдийн мэдэх байдлаар салгаж болно.

In [ ]:
df['Section'] = None

In [ ]:
df.loc[df['Address'].str.contains('ЧД|ЧИН|CHIN', case=False), 'Section'] = 'Чингэлтэй' 
df.loc[df['Address'].str.contains('СБД|SBD|SUKHBAA', case=False), 'Section'] = 'Сүхбаатар' 
df.loc[df['Address'].str.contains('БЗД|БАЯНЗҮ|BZD', case=False), 'Section'] = 'Баянзүрх' 
df.loc[df['Address'].str.contains('СХД|СОНГИНО|SHD', case=False), 'Section'] = 'Сонгинохайрхан' 
df.loc[df['Address'].str.contains('БГД|БАЯНГО|BGD', case=False), 'Section'] = 'Баянгол' 
df.loc[df['Address'].str.contains('ХУД|ХАН-|ХАНУУ|ХАН УУ|HUD', case=False), 'Section'] = 'Хан-Уул' 
df.loc[df['Address'].str.contains('НАЛАЙХ', case=False), 'Section'] = 'Налайх' 
df.loc[df['Address'].str.contains('БАГАНУУР|BAGANUUR', case=False), 'Section'] = 'Багануур' 

# гэх энгийн логикоос эхэлнэ

In [ ]:
# доорх кодоор цэвэрлэгдээгүй хэсгийг шалгана
remaining = df[df['Section'].isna()]

print("Цэвэрлэгдээгүй үлдэгдэл", remaining.shape)
remaining['Address'].head(20)
# эсвэл түүвэрлэж шалгаж болно
remaining.sample(20)

# үүнээсээ address баганы утганд үндэслэн нэмэлт нөхцөлүүдийг бичиж цэвэрлэж болно
# эсвэл remaining['addr_2'] = remaining['Address'].str.split().str[:2].str.join(' ') кодоор address баганы эхний 2 үгийг шинэ addr_2 баганад авчирч
# remaining['addr_2'].value_counts() кодоор давхардлыг нь шалгаж болно
# ингэснээр цэвэрлэхэд хялбар болно

# .str[:3] гэх мэтчилэн эхний 3 үгээр давхардал шалгасан ч болно

## Fuzzy matching 

SANSR
SANSAAR
SANSEER
гэх мэт ялгаатай байдлаар алдаатай бичигдсэн үгсийг бүлэглэхдээ fuzzy matching ашиглах боломжтой

In [ ]:
#!pip install rapidfuzz
# доор package import хийх үед алдаа гарвал дээрх pip install командыг ажиллуулж package-ийг суулгана уу

In [ ]:
from rapidfuzz import process

choices = ['САНСАР', 'ЖУКОВ', 'ЯАРМАГ', 'ЗАЙСАН']

def fuzzy_match(x):
    if pd.isna(x):
        return None
    match, score, _ = process.extractOne(x, choices)
    if score > 85:
        # 85-г өөрчилж болно
        return match
    return None

df['fuzzy_area'] = df['Address'].apply(fuzzy_match)

## Validation

Хаягаа цэвэрлэж дууссаны дараагаар (дор хаяж 80%) цэвэрлэсэн кодоо баталгаажуулахдаа дор хаяж 50 мөр ихдээ 300 мөр (ойролцоогоор датаны 1-2%)-ыг гараар шалгаж баталгаажуулдаг.

Ингэхдээ санамсаргүй түүвэр буюу .sample() функцийг ашиглана.

In [ ]:
# print(df['Section'].value_counts())
# df.sample(20)

## Нэмэлт хэрэгцээтэй функцүүд

In [2]:
df = pd.DataFrame({
    'Product_ID': [101, 102, 103, 104],
    'Brand': ['ColaX', 'Yogurty', 'IcePop', 'Snacky'],
    'Flavors': [
        'Cola, Cherry, Vanilla',
        'Strawberry / Blueberry',
        'Mango; Pineapple | Orange',
        'BBQ\nCheese\nSour Cream'
    ],
    'Price': [1.5, 2.3, 0.8, 1.2]
})

In [3]:
df.head()

   Product_ID    Brand                    Flavors  Price
0         101    ColaX      Cola, Cherry, Vanilla    1.5
1         102  Yogurty     Strawberry / Blueberry    2.3
2         103   IcePop  Mango; Pineapple | Orange    0.8
3         104   Snacky    BBQ\nCheese\nSour Cream    1.2

In [4]:
# Текстийг эхлээд стандартжуулна

df['Flavors'] = df['Flavors'].str.upper().str.strip()

In [5]:
df.head()

   Product_ID    Brand                    Flavors  Price
0         101    ColaX      COLA, CHERRY, VANILLA    1.5
1         102  Yogurty     STRAWBERRY / BLUEBERRY    2.3
2         103   IcePop  MANGO; PINEAPPLE | ORANGE    0.8
3         104   Snacky    BBQ\nCHEESE\nSOUR CREAM    1.2

In [6]:
# Flavors баганы утгыг , / ; | \n тэмдэгтүүдээр салгаж шинэ Flavor_list баганад хадгална
df['Flavor_list'] = df['Flavors'].str.split(r'[,/;|\n]')

df.head()

,Product_ID,Brand,Flavors,Price,Flavor_list
0,101,ColaX,"COLA, CHERRY, VANILLA",1.5,"[COLA, CHERRY, VANILLA]"
1,102,Yogurty,STRAWBERRY / BLUEBERRY,2.3,"[STRAWBERRY , BLUEBERRY]"
2,103,IcePop,MANGO; PINEAPPLE | ORANGE,0.8,"[MANGO, PINEAPPLE , ORANGE]"
3,104,Snacky,BBQ\nCHEESE\nSOUR CREAM,1.2,"[BBQ, CHEESE, SOUR CREAM]"

In [7]:
# Flavor_list баганы лист болгоны элементийн дагуу шинэ мөр үүсгэж өгнө
df = df.explode('Flavor_list')

In [8]:
df.head()

   Product_ID    Brand                 Flavors  Price  Flavor_list
0         101    ColaX   COLA, CHERRY, VANILLA    1.5         COLA
0         101    ColaX   COLA, CHERRY, VANILLA    1.5       CHERRY
0         101    ColaX   COLA, CHERRY, VANILLA    1.5      VANILLA
1         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3  STRAWBERRY
1         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3    BLUEBERRY

In [9]:
# Листийн элементийн эхэнд болон төгсгөлд хоосон зай байвал арилгана
df['Flavor_list'] = df['Flavor_list'].str.strip()

In [10]:
# Баганы шинэ нэр
df = df.rename(columns={'Flavor_list': 'Flavor'})

In [11]:
df.head()

   Product_ID    Brand                 Flavors  Price      Flavor
0         101    ColaX   COLA, CHERRY, VANILLA    1.5        COLA
0         101    ColaX   COLA, CHERRY, VANILLA    1.5      CHERRY
0         101    ColaX   COLA, CHERRY, VANILLA    1.5     VANILLA
1         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3  STRAWBERRY
1         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3   BLUEBERRY

In [12]:
# Индексийг шинэчлэх бол (0-ээс эхлээд шинээр дугаарлах)

df = df.reset_index(drop=True)

In [13]:
print(df.shape)

df.head()

(11, 5)

   Product_ID    Brand                 Flavors  Price      Flavor
0         101    ColaX   COLA, CHERRY, VANILLA    1.5        COLA
1         101    ColaX   COLA, CHERRY, VANILLA    1.5      CHERRY
2         101    ColaX   COLA, CHERRY, VANILLA    1.5     VANILLA
3         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3  STRAWBERRY
4         102  Yogurty  STRAWBERRY / BLUEBERRY    2.3   BLUEBERRY